pool:
  vmImage: windows-2019
steps:
  - checkout: self
    clean: true
    lfs: false
    fetchDepth: 1
    submodules: false
  - script: make tools
    displayName: Install build tools
  - script: make src
    displayName: Build addons
  - script: make test
    displayName: Run tests
    env:
      CI: true
      NODE_NO_WARNINGS: 1
