pool:
  vmImage: windows-2019
steps:
  - checkout: self
    clean: true
    lfs: false
    fetchDepth: 1
    submodules: false
  - powershell: iwr ftp://ftp.equation.com/make/64/make.exe -out make.exe; .\make.exe install
    displayName: make install
  - script: .\make.exe configure
    displayName: make configure
  - script: .\make.exe build
    displayName: make build
  - powershell: .\make.exe test -j($env:NUMBER_OF_PROCESSORS)
    displayName: make test
    env:
      CI: true
      NODE_NO_WARNINGS: 1
