pool:
  vmImage: windows-2019
steps:
  - checkout: self
    clean: true
    lfs: true
    fetchDepth: 1
  - powershell: .\setup.ps1
    displayName: Setup dependencies
  - script: make tools
    displayName: Install build tools
  - script: make src
    displayName: Build addons
  - script: make test
    displayName: Run tests
    env:
      CI: true
      NODE_NO_WARNINGS: 1
